1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

необходимо, чтобы число столбцов матрицы  𝐴  было равно числу строк матрицы  𝐵 .

В частности, определить оба произведения  𝐴⋅𝐵  и  𝐵⋅𝐴  можно только в случае, когда число столбцов  𝐴  совпадает с числом строк  𝐵 , а число строк  𝐴  совпадает с числом столбцов  𝐵 . В этом случае матрицы  𝐴⋅𝐵  и  𝐵⋅𝐴  будут квадратными.

Следовательно:
    
    а) оба произведения не определены
    б) определено произведение BA, результат - матрица 5х5
    в)определено произвдение AB, результат - матрица 8x8
    г) Определены оба произведения, результат - матрица 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
import numpy as np

In [3]:
a = np.array([[1, -2], [3, 0]])
b= np.array ([[4, -1], [0, 5]])

In [5]:
a+b

array([[ 5, -3],
       [ 3,  5]])

In [6]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

In [7]:
np.dot(b, a)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
a = np.array([[1, 7], [3, -6]])
b= np.array ([[0, 5], [2, -1]])
c=np.array ([[2, -4], [1, 1]])

In [9]:
result = 3*a-2*b+4*c

In [10]:
result

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [12]:
a = np.array([[4, 1], [5, -2],[2,3]])

In [13]:
np.dot(a, a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [14]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

1. Вычислить определитель:

a) detA = sin^2(x)+cos^2(x) = 1

б) detA = 0x(2x9-3x5)-0x(4x1-3x0)+9x(4x5-2x0)= 180

In [15]:
A = np.array([[4, 2, 3], [0, 5, 1],[0,0,9]])
detA = np.linalg.det(A)

In [16]:
detA

180.0

в) detA = 1x(5x9-6x8)-2x(4x9-6x7)+3x(4x8-5x7) = 0

In [26]:
1*(5*9-6*8)-2*(4*9-6*7)+3*(4*8-5*7)

0

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


2. Определитель матрицы  𝐴  равен  4 . Найти:

а)  𝑑𝑒𝑡(𝐴^2) ;

б)  𝑑𝑒𝑡(𝐴𝑇) ;

в)  𝑑𝑒𝑡(2𝐴) .

a) Для двух квадратных матриц одинакового размера

𝑑𝑒𝑡(𝐴𝐵)=𝑑𝑒𝑡𝐴⋅𝑑𝑒𝑡𝐵.

следовательно det (AA)= detAxdetA = 4*4 = 16

б)Определитель транспонированной матрицы равен определителю исходной:

𝑑𝑒𝑡𝐴𝑇=𝑑𝑒𝑡𝐴.
следовательно ответ = 4

в) Умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число.
следовательно det (2A) = 2xdet(A) = 8

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


Матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

In [30]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

a) 3я строка является сумммой 1й и 2й срок, т.е ее можно удалить. Затем из первой строки можно вычесть вторую, получим матрицу

$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
\end{pmatrix};$

ранг которой равен 2

In [33]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


б) 3я  строка является суммой первой и второй строк, удаляем 3ю строку, получаем матрицу

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$ 
ранг которой =3


In [34]:
a = np.array([[0, 0, 2,1], [0, 0, 2,2], [0, 0, 4,3], [2,3,5,6]])
print(f'Матрица:\n{a}')
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
